from pathlib import Path

p=Path('scripts/athlete-attributes-v1.js')
text=p.read_text(encoding='utf-8')
repls={
"if(validMark(top)&&isBetterValue(a,mark,top))return Math.round(interpolateMark(a,mark,top,18,eliteMark||top,20));\n if(isBetterValue(a,mark,world))return Math.round(interpolateMark(a,mark,world,17,top||world,18));\n if(isBetterValue(a,mark,international))return Math.round(interpolateMark(a,mark,international,15,world,17));\n if(isBetterValue(a,mark,national))return Math.round(interpolateMark(a,mark,national,13,international,15));\n const development=lowerIsBetter(a)?national*1.18:national*.82;\n if(isBetterValue(a,mark,development))return Math.round(interpolateMark(a,mark,development,7,national,13));\n const raw=lowerIsBetter(a)?national*1.35:national*.68;\n if(isBetterValue(a,mark,raw))return Math.round(interpolateMark(a,mark,raw,4,development,7));":"if(validMark(top)&&isBetterValue(a,mark,top))return Math.round(interpolateMark(a,mark,top,18,eliteMark||top,20));\n if(isBetterValue(a,mark,world))return Math.round(interpolateMark(a,mark,world,16,top||world,18));\n if(isBetterValue(a,mark,international))return Math.round(interpolateMark(a,mark,international,14,world,16));\n if(isBetterValue(a,mark,national))return Math.round(interpolateMark(a,mark,national,12,international,14));\n const development=lowerIsBetter(a)?national*1.18:national*.82;\n if(isBetterValue(a,mark,development))return Math.round(interpolateMark(a,mark,development,6,national,12));\n const raw=lowerIsBetter(a)?national*1.35:national*.68;\n if(isBetterValue(a,mark,raw))return Math.round(interpolateMark(a,mark,raw,3,development,6));",
"function calibratedBase(a){\n const performance=performanceRating(a),legacy=legacyBridgeRating(a);\n if(!Number.isFinite(performance))return legacy;\n /* PB/standards own 85% of the bridge. Legacy strength can move the result by roughly one point,\n    but it can no longer manufacture elite attributes unsupported by actual performance. */\n return clamp(Math.round(performance*.85+legacy*.15),3,20);\n}":"function calibratedBase(a){\n const performance=performanceRating(a);\n /* Objective performance owns the visible scale. The old hidden rating is fallback data only when\n    an athlete genuinely has no usable PB/standard evidence. */\n return Number.isFinite(performance)?clamp(Math.round(performance),3,20):legacyBridgeRating(a);\n}",
"function eliteCaps(performanceLevel){\n const level=Number(performanceLevel)||0;\n if(level>=19)return{max:20,twenties:2,nineteenPlus:4};\n if(level>=18)return{max:20,twenties:1,nineteenPlus:2};\n if(level>=17)return{max:19,twenties:0,nineteenPlus:1};\n if(level>=16)return{max:18,twenties:0,nineteenPlus:0};\n if(level>=14)return{max:17,twenties:0,nineteenPlus:0};\n if(level>=12)return{max:16,twenties:0,nineteenPlus:0};\n if(level>=10)return{max:14,twenties:0,nineteenPlus:0};\n return{max:12,twenties:0,nineteenPlus:0};\n}":"function eliteCaps(performanceLevel){\n const level=Number(performanceLevel)||0;\n if(level>=20)return{max:20,twenties:1,nineteenPlus:3};\n if(level>=19)return{max:19,twenties:0,nineteenPlus:2};\n if(level>=18)return{max:19,twenties:0,nineteenPlus:1};\n if(level>=17)return{max:18,twenties:0,nineteenPlus:0};\n if(level>=16)return{max:17,twenties:0,nineteenPlus:0};\n if(level>=14)return{max:16,twenties:0,nineteenPlus:0};\n if(level>=12)return{max:15,twenties:0,nineteenPlus:0};\n if(level>=9)return{max:13,twenties:0,nineteenPlus:0};\n return{max:11,twenties:0,nineteenPlus:0};\n}",
"function band(score){const n=Number(score)||0;if(n>=20)return'elite';if(n>=18)return'excellent';if(n>=16)return'strong';if(n>=13)return'solid';if(n>=10)return'developing';return'limited'}\nfunction bandLabel(score){const n=Number(score)||0;if(n>=20)return'World Class';if(n>=18)return'Elite International';if(n>=16)return'International';if(n>=13)return'National';if(n>=10)return'Domestic';if(n>=7)return'Developing';return'Raw'}":"function band(score){const n=Number(score)||0;if(n>=20)return'elite';if(n>=18)return'excellent';if(n>=15)return'strong';if(n>=12)return'solid';if(n>=9)return'developing';return'limited'}\nfunction bandLabel(score){const n=Number(score)||0;if(n>=20)return'Exceptional';if(n>=18)return'Elite International';if(n>=15)return'International';if(n>=12)return'National';if(n>=9)return'Domestic';if(n>=6)return'Developing';return'Raw'}",
"eliteRule:'20 is world-class and capped at two attributes per athlete',bands:{20:'World Class','18-19':'Elite International','16-17':'International','13-15':'National','10-12':'Domestic','7-9':'Developing','1-6':'Raw'}":"eliteRule:'20 requires exceptional event performance and is capped at one attribute per athlete',bands:{20:'Exceptional','18-19':'Elite International','15-17':'International','12-14':'National','9-11':'Domestic','6-8':'Developing','1-5':'Raw'}"
}
for old,new in repls.items():
    if old not in text: raise SystemExit('attribute calibration anchor not found: '+old[:80])
    text=text.replace(old,new,1)
p.write_text(text,encoding='utf-8')

p=Path('tools/runtime-smoke.mjs')
text=p.read_text(encoding='utf-8')
old="""   if(audit.maxTwenties>2)fail(`Athlete Attributes elite-rarity rule failed: one athlete has ${audit.maxTwenties} ratings of 20.`);
   const twentyShare=audit.totalScores?audit.twenties/audit.totalScores:0;
   if(twentyShare>.04)fail(`Athlete Attributes calibration is too generous: ${(twentyShare*100).toFixed(1)}% of all ratings are 20.`);
"""
new="""   if(audit.maxTwenties>1)fail(`Athlete Attributes elite-rarity rule failed: one athlete has ${audit.maxTwenties} ratings of 20.`);
   if(audit.multipleTwenties>0)fail(`Athlete Attributes elite-rarity rule failed: ${audit.multipleTwenties} athletes have multiple 20 ratings.`);
   const twentyShare=audit.totalScores?audit.twenties/audit.totalScores:0;
   if(twentyShare>.01)fail(`Athlete Attributes calibration is too generous: ${(twentyShare*100).toFixed(1)}% of all ratings are 20.`);
   if(audit.average>14.5)fail(`Athlete Attributes database average is too high at ${audit.average}/20.`);
"""
if old not in text: raise SystemExit('runtime calibration threshold anchor not found')
p.write_text(text.replace(old,new,1),encoding='utf-8')
