/* Athletics Manager — Calendar V2
   Season planning replacement using authoritative event/plan/decision state.
   Legacy Calendar remains retained as fallback until parity QA is complete. */
(function(){
'use strict';
if(window.__amCalendarV2)return;window.__amCalendarV2=1;
if(typeof drawCalendar!=='function')return;

const legacyDrawCalendar=drawCalendar;
const $=id=>document.getElementById(id);
const esc=v=>{try{return profileEscape(String(v??''))}catch(_){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}};
const nowWeek=()=>Number(s?.game?.week||1);
const season=()=>Number(s?.game?.season||new Date().getUTCFullYear());
const core=()=>window.__athleticsInboxDecisionCore;
let cancelArmed=null;
function safe(fn,fallback){try{const v=fn();return v==null?fallback:v}catch(_){return fallback}}
function state(){const x=s.uiCalendarV2??={};if(!Number.isFinite(Number(x.selectedWeek)))x.selectedWeek=nowWeek();x.selectedWeek=Math.max(1,Math.min(52,Number(x.selectedWeek)));x.filter=x.filter||'all';x.showPast=!!x.showPast;return x}
function saveSafe(){try{save()}catch(_){}}
function actions(){return safe(()=>core()?.getUnresolvedActions?.()||[],[])}
function plans(){return safe(()=>planList(),s.plans||[])}
function team(){return safe(()=>managedTeam(),[])}
function startDate(w){return safe(()=>weekDate(w,season()),new Date(Date.UTC(season(),0,1+(Number(w)-1)*7)))}
function shortDate(w){return startDate(w).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})}
function rangeDate(w){const a=startDate(w),b=new Date(a.getTime()+6*86400000);return `${a.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})} – ${b.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})}`}
function eventKind(e){return ['competition','championship','olympics','testing','scout','review'].includes(e?.kind)?e.kind:'competition'}
function eventAction(e,acts=actions()){return acts.find(a=>String(a.entityId)===String(e?.id)&&['competition','summit'].includes(String(a.source)))||null}
function dueActions(w,acts=actions()){return acts.filter(a=>Number(a.deadline)===Number(w))}
function weekEvents(w){return (s.events||[]).filter(e=>Number(e.week)===Number(w))}
function planEnd(p){const c=safe(()=>CAMP_OPTIONS[p.type],null);return Number(p.week)+(p.kind==='camp'?(Number(c?.weeks)||1):1)-1}
function weekPlans(w){return plans().filter(p=>Number(p.season)===season()&&p.status!=='cancelled'&&Number(p.week)<=w&&planEnd(p)>=w)}
function leagueRound(w){return [17,19,21].includes(Number(w))}
function kindLabel(kind){return ({competition:'Competition',championship:'Championship',olympics:'Olympic Games',testing:'Testing',scout:'Scouting',review:'Review',camp:'Training Camp',league:'Summit Series'})[kind]||'Programme'}
function eventState(e){if(e.completed)return['Complete','good'];if(Number(e.week)<nowWeek())return['Past',''];if(Number(e.week)===nowWeek())return['This week','live'];const a=eventAction(e);if(a)return[a.blocks?'Action due':'Decision open',a.blocks?'action':''];return[`Week ${e.week}`,'']}
function resultSummary(e){const discs=(e.disc||[]).filter(d=>d!=='ALL'),done=discs.filter(d=>Array.isArray(e.results?.[d]));let podiums=0;for(const d of done)for(const row of e.results[d]||[])if(row?.nation===safe(()=>managedNation(),'')&&Number(row.place||0)<=3&&Number(row.place||0)>0)podiums++;return {done:done.length,total:discs.length,podiums}}
function weekHasCompetition(w){return weekEvents(w).some(e=>['competition','championship','olympics'].includes(e.kind))||leagueRound(w)}
function weekHasProgramme(w){return weekPlans(w).length||weekEvents(w).some(e=>['testing','scout','review'].includes(e.kind))}
function weekVisible(w,filter,acts){const st=state();if(!st.showPast&&w<nowWeek()-1&&w!==st.selectedWeek)return false;if(filter==='competition')return weekHasCompetition(w);if(filter==='programme')return !!weekHasProgramme(w);if(filter==='actions')return dueActions(w,acts).length>0||weekEvents(w).some(e=>!!eventAction(e,acts));return true}
function itemHTML(kind,title,meta=''){return `<div class="calv2-item"><i class="calv2-dot ${esc(kind)}"></i><strong title="${esc(title)}">${esc(title)}</strong>${meta?`<small>${esc(meta)}</small>`:''}</div>`}
function weekStatus(w,ev,ps,acts){const due=dueActions(w,acts);if(due.length)return `<span class="calv2-state action">${due.length} action${due.length===1?'':'s'}</span>`;if(w===nowWeek())return '<span class="calv2-state live">Current</span>';if(ev.length&&ev.every(e=>e.completed))return '<span class="calv2-state good">Complete</span>';if(ps.some(p=>p.status==='scheduled'))return '<span class="calv2-state">Planned</span>';return ''}
function weekRow(w,acts){const ev=weekEvents(w),ps=weekPlans(w),round=leagueRound(w),st=state(),due=dueActions(w,acts),items=[];ev.slice(0,3).forEach(e=>items.push(itemHTML(eventKind(e),e.name,kindLabel(eventKind(e)))));ps.slice(0,2).forEach(p=>items.push(itemHTML(p.kind==='camp'?'camp':'testing',p.kind==='camp'?(safe(()=>CAMP_OPTIONS[p.type].name,'Training camp')):'Squad testing',p.status)));if(round)items.push(itemHTML('league','Summit Series round','Series'));if(due.length&&!ev.some(e=>due.some(a=>String(a.entityId)===String(e.id))))items.push(itemHTML('review',due[0].title,'Decision deadline'));if(items.length>4)items.length=4;return `<article class="calv2-week ${w===st.selectedWeek?'selected':''} ${w===nowWeek()?'current':''} ${w<nowWeek()?'past':''} ${due.length?'has-action':''}" data-calv2-week-row="${w}"><button class="calv2-week-open" data-calv2-week="${w}" aria-label="Open Week ${w}"><b>W${w}</b><small>${esc(shortDate(w))}</small></button><div class="calv2-week-body">${items.join('')||'<span class="calv2-free">No scheduled programme activity</span>'}</div><div class="calv2-week-state">${weekStatus(w,ev,ps,acts)}</div></article>`}
function eventDetail(e,acts){const [label,cls]=eventState(e),a=eventAction(e,acts),sum=resultSummary(e),current=Number(e.week)===nowWeek()&&!e.completed&&['competition','championship','olympics'].includes(e.kind),future=Number(e.week)>nowWeek();const discs=(e.disc||[]).filter(d=>d!=='ALL');return `<section class="calv2-detail-item"><div class="calv2-detail-top"><small>${esc(kindLabel(eventKind(e)))} · ${esc(e.level||'Programme')}</small><span class="calv2-state ${cls}">${esc(label)}</span></div><h3>${esc(e.name)}</h3><p>${esc(e.location||'Venue TBC')} · ${discs.length?`${discs.length} discipline${discs.length===1?'':'s'}`:'Programme event'}${e.ranked?' · Ranking points':''}</p>${a?`<div class="calv2-action-note"><span>!</span><div><b>${esc(a.title)}</b><br>${esc(a.reason||'A manager decision is required.')}</div></div>`:''}${e.completed?`<div class="calv2-result-strip"><span><b>${sum.done}/${sum.total}</b> disciplines recorded</span><span><b>${sum.podiums}</b> programme podiums</span></div>`:''}<div class="calv2-detail-actions">${a?`<button class="btn primary" data-calv2-action="${esc(a.actionId)}">${a.blocks?'RESOLVE DECISION':'OPEN DECISION'}</button>`:''}${current?'<button class="btn primary" data-calv2-event>OPEN EVENT DAY</button>':future&&!a?`<button class="btn ghost" disabled title="This competition is not active yet">OPENS WEEK ${Number(e.week)}</button>`:''}${e.completed?'<span class="calv2-state good">RESULTS RECORDED</span>':''}</div></section>`}
function selectedWeekHTML(w,acts){const ev=weekEvents(w),ps=weekPlans(w),due=dueActions(w,acts),round=leagueRound(w);return `<section class="calv2-card calv2-week-detail"><header><div><small class="calv2-eyebrow">SELECTED WEEK</small><h2>Week ${w}</h2><p>${esc(rangeDate(w))} · ${season()}</p></div>${w===nowWeek()?'<span class="calv2-now">Current week</span>':''}</header><div class="calv2-detail-list">${due.filter(a=>!ev.some(e=>String(e.id)===String(a.entityId))).map(a=>`<section class="calv2-detail-item"><div class="calv2-detail-top"><small>Management deadline</small><span class="calv2-state action">Action required</span></div><h3>${esc(a.title)}</h3><p>${esc(a.reason||'A manager decision is due this week.')}</p><div class="calv2-detail-actions"><button class="btn primary" data-calv2-action="${esc(a.actionId)}">OPEN DECISION</button></div></section>`).join('')}${ev.map(e=>eventDetail(e,acts)).join('')}${round?'<section class="calv2-detail-item"><div class="calv2-detail-top"><small>Summit Series</small><span class="calv2-state">Series round</span></div><h3>Summit Series Meeting</h3><p>Series commitments and entries are managed from the Summit Series screen.</p><div class="calv2-detail-actions"><button class="btn ghost" data-calv2-league>OPEN SUMMIT SERIES</button></div></section>':''}${ps.map(p=>planDetail(p)).join('')}${!due.length&&!ev.length&&!round&&!ps.length?'<div class="calv2-empty">No events, decisions or programme activities are scheduled for this week.</div>':''}</div></section>`}
function planDetail(p){const title=p.kind==='camp'?safe(()=>CAMP_OPTIONS[p.type].name,'Training camp'):'Squad testing';const names=(p.ids||[]).map(id=>s.athletes?.find(a=>a.id===id)?.name||'Former athlete');return `<section class="calv2-detail-item"><div class="calv2-detail-top"><small>${p.kind==='camp'?'High Performance':'Testing'} · ${esc(p.status||'scheduled')}</small><span class="calv2-state ${p.status==='complete'?'good':''}">${esc(p.status||'scheduled')}</span></div><h3>${esc(title)}</h3><p>${esc(names.join(', ')||'No athletes')} · ${p.kind==='camp'?`Weeks ${p.week}–${planEnd(p)}`:'Practice testing day'}</p>${p.results?.length?`<div class="calv2-result-strip"><span><b>${p.results.length}</b> testing records</span></div>`:''}</section>`}
function bookingList(){const rows=plans().filter(p=>Number(p.season)===season()&&p.status!=='cancelled').sort((a,b)=>Math.abs(Number(a.week)-nowWeek())-Math.abs(Number(b.week)-nowWeek())||Number(a.week)-Number(b.week)).slice(0,8);return `<section class="calv2-card"><div class="calv2-card-head"><strong>Programme Bookings</strong><span>${rows.length?`${rows.length} shown`:'Season plans'}</span></div><div class="calv2-bookings">${rows.length?rows.map(p=>{const title=p.kind==='camp'?safe(()=>CAMP_OPTIONS[p.type].name,'Training camp'):'Squad testing';const names=(p.ids||[]).map(id=>s.athletes?.find(a=>a.id===id)?.name||'Former athlete').join(', ');const armed=cancelArmed===p.id;return `<div class="calv2-booking"><time>W${Number(p.week)}</time><div><strong>${esc(title)} · ${esc(p.status)}</strong><small title="${esc(names)}">${esc(names||'No athletes')}</small></div>${p.status==='scheduled'?`<button class="${armed?'confirm':''}" data-calv2-cancel="${esc(p.id)}">${armed?'CONFIRM CANCEL':'CANCEL'}</button>`:''}</div>`}).join(''):'<div class="calv2-empty">No programme activities booked this season.</div>'}</div></section>`}
function plannerHTML(w){if(w<nowWeek())return `<section class="calv2-card"><div class="calv2-card-head"><strong>Plan Activity</strong><span>Week ${w}</span></div><div class="calv2-empty">This week has passed. Existing results and history remain available above.</div></section>`;const opts=Object.entries(safe(()=>CAMP_OPTIONS,{}));const athletes=team();return `<section class="calv2-card"><div class="calv2-card-head"><strong>Plan Activity</strong><span>Week ${w}</span></div><div class="calv2-planner"><div class="calv2-planner-grid"><label>Activity<select id="calv2PlanKind"><option value="camp">Training camp</option><option value="testing">Squad testing day</option></select></label><label id="calv2CampLabel">Programme<select id="calv2PlanCamp">${opts.map(([k,c])=>`<option value="${esc(k)}">${esc(c.name)} · ${esc(safe(()=>money(c.cost),`£${Number(c.cost).toLocaleString('en-GB')}`))}</option>`).join('')}</select></label><div class="calv2-planner-group"><strong>Athletes</strong><div class="calv2-athletes">${athletes.length?athletes.map(a=>`<label><input type="checkbox" data-calv2-athlete="${esc(a.id)}" ${a.injury>0?'disabled':''}><span>${esc(a.name)}</span><em>${a.injury>0?`Injured ${a.injury}w`:esc(safe(()=>discLabel(a.disc),a.disc))}</em></label>`).join(''):'<div class="calv2-empty">No managed athletes available.</div>'}</div></div><div id="calv2Preview" class="calv2-preview">Choose athletes to see the booking impact.</div><div id="calv2DisabledReason" class="calv2-disabled-reason"></div><div class="calv2-planner-actions"><button id="calv2Book" class="btn primary">BOOK ACTIVITY</button></div></div></div></section>`}
function renderCalendar(){const root=$('calendar');if(!root)return;const st=state(),acts=actions();planningWeek=st.selectedWeek;const weeks=Array.from({length:52},(_,i)=>i+1).filter(w=>weekVisible(w,st.filter,acts));const futureEvents=(s.events||[]).filter(e=>!e.completed&&Number(e.week)>=nowWeek()).length;const planned=plans().filter(p=>Number(p.season)===season()&&p.status==='scheduled').length;root.innerHTML=`<div class="calv2" data-am-ui-screen="calendar-v2"><header class="calv2-head"><div class="calv2-title"><small>${esc(safe(()=>nationName(managedNation()),'National Programme').toUpperCase())} · SEASON PLANNING</small><h1>Calendar</h1><p>${season()} · Week ${nowWeek()} · ${esc(rangeDate(nowWeek()))}</p></div><div class="calv2-context"><span><small>Upcoming</small><b>${futureEvents}</b></span><span><small>Decisions</small><b>${acts.length}</b></span><span><small>Bookings</small><b>${planned}</b></span></div></header><div class="calv2-toolbar"><div class="calv2-filters" role="tablist" aria-label="Calendar filters">${[['all','All Weeks'],['competition','Competitions'],['programme','Programme'],['actions','Decisions']].map(([k,l])=>`<button class="${st.filter===k?'on':''}" data-calv2-filter="${k}">${l}</button>`).join('')}</div><div><button class="calv2-quiet" data-calv2-today>TODAY · W${nowWeek()}</button><button class="calv2-quiet" data-calv2-past>${st.showPast?'HIDE EARLY WEEKS':'SHOW FULL SEASON'}</button></div></div><div class="calv2-grid"><section class="calv2-card"><div class="calv2-card-head"><strong>Season Timeline</strong><span>${weeks.length} week${weeks.length===1?'':'s'} shown</span></div><div class="calv2-timeline" id="calv2Timeline">${weeks.length?weeks.map(w=>weekRow(w,acts)).join(''):'<div class="calv2-empty">No weeks match this filter. Clear the filter to see the full season.</div>'}</div></section><aside class="calv2-side">${selectedWeekHTML(st.selectedWeek,acts)}${plannerHTML(st.selectedWeek)}${bookingList()}</aside></div></div>`;bind(root,acts);window.AthleticsUI?.registerScreen?.('calendar',{status:'candidate',replacement:'calendar-v2'});}
function selectedIds(root){return [...root.querySelectorAll('[data-calv2-athlete]:checked')].map(x=>x.dataset.calv2Athlete)}
function plannerPreview(root){const kind=$('calv2PlanKind')?.value||'camp',campKey=$('calv2PlanCamp')?.value,c=safe(()=>CAMP_OPTIONS[campKey],null),ids=selectedIds(root),w=state().selectedWeek,end=w+(kind==='camp'?(Number(c?.weeks)||1):1)-1,label=$('calv2CampLabel'),preview=$('calv2Preview'),reason=$('calv2DisabledReason'),book=$('calv2Book');if(label)label.hidden=kind!=='camp';if(!preview||!book)return;const conflicts=[];for(const id of ids){const a=s.athletes?.find(x=>String(x.id)===String(id));if(!a)continue;safe(()=>commitmentConflicts(a,w,end),[]).forEach(x=>conflicts.push(x));if(a.injury>0)conflicts.push(`${a.name} is injured`);if(safe(()=>planOverlap(id,w,end),false))conflicts.push(`${a.name} already has a programme booking`)}const cost=kind==='camp'?(Number(c?.cost)||0)*ids.length:0;const budget=Number(s.funding||0);const invalid=[];if(!ids.length)invalid.push('Choose at least one athlete.');if(end>52)invalid.push('This activity would run beyond Week 52.');if(cost>budget)invalid.push('There is not enough programme funding for this booking.');if(conflicts.length)invalid.push('Selected athletes have conflicting commitments.');preview.textContent=kind==='camp'?`${c?.name||'Training camp'} · Week ${w}${end>w?`–${end}`:''} · ${ids.length} athlete${ids.length===1?'':'s'} · ${safe(()=>money(cost),`£${cost.toLocaleString('en-GB')}`)}. ${c?.desc||''}${conflicts.length?` Conflicts: ${[...new Set(conflicts)].join(', ')}.`:''}`:`Squad testing · Week ${w} · ${ids.length} athlete${ids.length===1?'':'s'} · no fee. Practice marks do not count as official records or ranking points.${conflicts.length?` Conflicts: ${[...new Set(conflicts)].join(', ')}.`:''}`;reason.textContent=invalid.join(' ');book.disabled=invalid.length>0;book.title=invalid.join(' ')||'Book this programme activity';}
function openAction(id,acts){const a=acts.find(x=>String(x.actionId)===String(id));if(!a)return;safe(()=>core()?.openAction?.(a),null)}
function cancelPlan(id){const p=plans().find(x=>String(x.id)===String(id));if(!p||p.status!=='scheduled')return;if(cancelArmed!==p.id){cancelArmed=p.id;renderCalendar();safe(()=>toast('Press Confirm Cancel to cancel this booking'),null);return}cancelArmed=null;p.status='cancelled';s.funding+=Number(p.cost)||0;safe(()=>recordFinance(Number(p.cost)||0,'Cancelled programme booking refund','Refund'),null);saveSafe();renderCalendar();safe(()=>toast('Programme booking cancelled'),null)}
function bind(root,acts){root.querySelectorAll('[data-calv2-week]').forEach(b=>b.addEventListener('click',()=>{const st=state();st.selectedWeek=Number(b.dataset.calv2Week);planningWeek=st.selectedWeek;saveSafe();renderCalendar()}));root.querySelectorAll('[data-calv2-filter]').forEach(b=>b.addEventListener('click',()=>{state().filter=b.dataset.calv2Filter;saveSafe();renderCalendar()}));root.querySelector('[data-calv2-today]')?.addEventListener('click',()=>{state().selectedWeek=nowWeek();state().filter='all';planningWeek=nowWeek();saveSafe();renderCalendar()});root.querySelector('[data-calv2-past]')?.addEventListener('click',()=>{state().showPast=!state().showPast;saveSafe();renderCalendar()});root.querySelectorAll('[data-calv2-action]').forEach(b=>b.addEventListener('click',()=>openAction(b.dataset.calv2Action,acts)));root.querySelectorAll('[data-calv2-event]').forEach(b=>b.addEventListener('click',()=>{competitionMode='overview';view('competition')}));root.querySelectorAll('[data-calv2-league]').forEach(b=>b.addEventListener('click',()=>view('league')));root.querySelectorAll('[data-calv2-cancel]').forEach(b=>b.addEventListener('click',()=>cancelPlan(b.dataset.calv2Cancel)));const kind=$('calv2PlanKind'),camp=$('calv2PlanCamp'),book=$('calv2Book');kind?.addEventListener('change',()=>plannerPreview(root));camp?.addEventListener('change',()=>plannerPreview(root));root.querySelectorAll('[data-calv2-athlete]').forEach(x=>x.addEventListener('change',()=>plannerPreview(root)));if(book)book.addEventListener('click',()=>{const ids=selectedIds(root),before=plans().length,w=state().selectedWeek;bookPlan(kind?.value||'camp',camp?.value,ids,w);if(plans().length===before)plannerPreview(root)});plannerPreview(root)}
function drawCandidate(){try{renderCalendar()}catch(err){console.error('[Athletics Manager] Calendar V2 recovered to legacy Calendar',err);legacyDrawCalendar();window.AthleticsUI?.registerScreen?.('calendar',{status:'fallback',replacement:'calendar-v2'})}}
drawCalendar=drawCandidate;
window.__athleticsCalendarV2={version:2,render:renderCalendar,legacy:legacyDrawCalendar,debug:()=>({selectedWeek:state().selectedWeek,filter:state().filter,actions:actions(),plans:plans().length})};
if(typeof currentView!=='undefined'&&currentView==='calendar')requestAnimationFrame(drawCandidate);
})();
