/* ===== Update #11: Endurance — core ===== */
(function(){
'use strict';
const ENDURANCE_VERSION=1;
const ED={
 M800:{label:"Men's 800m",type:'time',unit:'s',distance:800},W800:{label:"Women's 800m",type:'time',unit:'s',distance:800},
 M1500:{label:"Men's 1500m",type:'time',unit:'s',distance:1500},W1500:{label:"Women's 1500m",type:'time',unit:'s',distance:1500},
 M5000:{label:"Men's 5000m",type:'time',unit:'s',distance:5000},W5000:{label:"Women's 5000m",type:'time',unit:'s',distance:5000},
 M10000:{label:"Men's 10,000m",type:'time',unit:'s',distance:10000},W10000:{label:"Women's 10,000m",type:'time',unit:'s',distance:10000}
};
const WR={M800:100.91,W800:113.28,M1500:206.00,W1500:229.04,M5000:755.36,W5000:840.20,M10000:1571.00,W10000:1731.45},IDS=Object.keys(ED);
Object.assign(DISCIPLINES,ED);Object.assign(WORLD_RECORDS,WR);
Object.assign(WORLD_COUNTRIES,{KENYA:{name:'Kenya',flag:'🇰🇪'},ETHIOPIA:{name:'Ethiopia',flag:'🇪🇹'},UGANDA:{name:'Uganda',flag:'🇺🇬'}});Object.assign(COUNTRIES,WORLD_COUNTRIES);Object.assign(FLAGS,Object.fromEntries(Object.entries(COUNTRIES).map(([k,v])=>[k,v.flag])));
window.ENDURANCE_DISCIPLINES=ED;window.ENDURANCE_IDS=IDS;window.isEnduranceDiscipline=d=>Object.hasOwn(ED,String(d||''));
if(typeof SELECTION_STANDARDS!=='undefined')Object.assign(SELECTION_STANDARDS,{M800:{National:106.5,International:104.8,World:103.8,Olympic:103.2},W800:{National:122.5,International:120.2,World:118.8,Olympic:118.2},M1500:{National:222,International:216.5,World:212.5,Olympic:210.5},W1500:{National:249,International:242.5,World:237.5,Olympic:235.5},M5000:{National:815,International:790,World:775,Olympic:768},W5000:{National:900,International:875,World:855,Olympic:848},M10000:{National:1700,International:1650,World:1615,Olympic:1600},W10000:{National:1900,International:1840,World:1795,Olympic:1778}});
if(typeof QUALIFICATION_TARGETS!=='undefined'){Object.assign(QUALIFICATION_TARGETS.worldcup.standards,{M800:104.2,W800:119.3,M1500:214,W1500:239,M5000:782,W5000:865,M10000:1630,W10000:1815});Object.assign(QUALIFICATION_TARGETS.olympics.standards,{M800:103.2,W800:118.2,M1500:210.5,W1500:235.5,M5000:768,W5000:848,M10000:1600,W10000:1778})}
const oldSprint=isSprintDiscipline;isSprintDiscipline=d=>oldSprint(d)||isEnduranceDiscipline(d);
if(STAFF_DEF?.sprint){STAFF_DEF.sprint.name='Track Coach';STAFF_DEF.sprint.desc='Improves sprint speed, endurance, pacing, speed-endurance and track-race readiness.'}if(FACILITY_DEF?.sprint){FACILITY_DEF.sprint.name='Track Centre';FACILITY_DEF.sprint.desc='Supports national-squad track athletes from 100m through 10,000m, improving weekly development and competition preparation.'}
const ADD={spring:['M800','W800','M1500','W1500'],euro:['M800','W800','M1500','W1500','M5000','W5000'],nationals:IDS,diamond:['M800','W800','M1500','W1500','M5000','W5000'],worldcup:IDS,development:IDS,olympics:IDS};
function expandEvent(e){e.disc=[...new Set([...(e.disc||[]),...(ADD[e.id]||[])])];return e}EVENTS_TEMPLATE.forEach(expandEvent);const oldMakeEvents=makeEvents;makeEvents=(y,n='GREAT BRITAIN',c=1)=>oldMakeEvents(y,n,c).map(expandEvent);
const ST={KENYA:98,ETHIOPIA:97,UGANDA:92,USA:88,'GREAT BRITAIN':87,FRANCE:84,GERMANY:82,AUSTRALIA:84,CANADA:82,SOUTH_AFRICA:81,JAPAN:79,JAMAICA:72};
const SUR={KENYA:['Kiprono','Cheruiyot','Kiplagat','Kiptoo'],ETHIOPIA:['Bekele','Tadesse','Kebede','Worku'],UGANDA:['Kiplimo','Cheptegei','Musagala','Kwemoi'],USA:['Fisher','Young','Hocker','Miller'],'GREAT BRITAIN':['Mills','Rowe','Atkinson','Clarke'],FRANCE:['Habz','Gressier','Robert','Klein'],GERMANY:['Farken','Klecker','Parsons','Hering'],AUSTRALIA:['McSweyn','Hoare','Stewart','Ramsden'],CANADA:['Arop','Knight','Ahmed','Stafford'],SOUTH_AFRICA:['Mphakathi','Mokoena','Mthembu','Dlamini'],JAPAN:['Tanaka','Endo','Mori','Yamamoto'],JAMAICA:['Campbell','Brown','Grant','Blake']};
const MF=['Daniel','Samuel','Elias','Noah'],FF=['Faith','Mary','Amina','Hannah'];
function pbFor(d,o,seed=0){const f=d[0]==='W',dist=ED[d].distance,x={800:[101.4,114,.72,.88],1500:[207.1,231,1.35,1.62],5000:[760,846,4.1,4.8],10000:[1586,1752,7.7,8.8]}[dist],noise=((seed%101)-50)/100*(dist>=5000?5:dist>=1500?1.6:.7);return +(x[f?1:0]+Math.max(0,96-o)*x[f?3:2]+noise).toFixed(2)}
function seedAthlete(n,d,i){const h=hashString(`${n}|${d}|end11`),f=d[0]==='W',dist=ED[d].distance,bias=dist===800?1:dist>=5000?((h>>5)%3-1):0,o=clamp((ST[n]||80)+bias+(h%5-2),68,97),surname=(SUR[n]||['Morgan','Silva','Martin','Lee'])[i%4];return{id:`end11-${n.toLowerCase().replace(/[^a-z]/g,'')}-${d.toLowerCase()}`,name:`${(f?FF:MF)[i%4]} ${surname}`,nation:n,disc:d,age:21+((h>>9)%9),overall:o,potential:clamp(o+((h>>4)%4),o,99),fitness:89+((h>>12)%9),form:80+((h>>15)%14),fatigue:8+((h>>18)%24),pb:pbFor(d,o,h),tier:o>=92?'Elite':o>=84?'International':'Developing',points:0,injury:0,medals:{g:0,s:0,b:0},training:'Balanced',inSquad:true,source:NATIONS[n]?'Established':'World',profileResults:[]}}
const SEED_N=['GREAT BRITAIN','USA','JAMAICA','GERMANY','CANADA','FRANCE','AUSTRALIA','JAPAN','SOUTH_AFRICA','KENYA','ETHIOPIA','UGANDA'],SEEDS=[];SEED_N.forEach(n=>IDS.forEach((d,i)=>SEEDS.push(seedAthlete(n,d,i))));
const oldMakeAthletes=makeAthletes;makeAthletes=()=>{const r=oldMakeAthletes(),ids=new Set(r.map(a=>a.id));SEEDS.forEach(a=>{if(!ids.has(a.id))r.push({...a,medals:{g:0,s:0,b:0},profileResults:[]})});return r};
const oldNewProspect=newProspect;newProspect=(n,f='All',l=1)=>{const a=oldNewProspect(n,f,l);if(isEnduranceDiscipline(a.disc))a.pb=+(pbFor(a.disc,clamp(a.overall+10,70,96),hashString(`${a.id}|end`))+(ED[a.disc].distance>=5000?20:ED[a.disc].distance>=1500?6:2)).toFixed(2);return a};
const oldFmt=fmtPerf;fmtPerf=(d,v)=>{if(!isEnduranceDiscipline(d))return oldFmt(d,v);v=Number(v)||0;const m=Math.floor(v/60),sec=v-m*60;return `${m}:${sec.toFixed(2).padStart(5,'0')}`};
const oldRaw=rawPerformance;rawPerformance=(a,d,staff=0)=>{if(!isEnduranceDiscipline(d))return oldRaw(a,d,staff);if(a&&a.nation!==managedNation()&&typeof rivalProgrammeSupport==='function')staff+=(rivalProgrammeSupport(a.nation,d)-2.5)*.32;const dist=ED[d].distance,cond=a.form*.34+a.fitness*.36+(100-a.fatigue)*.30+(athleteMorale(a)-65)*.08,scale=Math.pow(dist/800,.62);return +Math.max(1,a.pb+rand(-.42,1.22)*scale+(82-cond)*.10*(dist/800)+(88-a.overall)*.025*scale-staff*.07*scale).toFixed(2)};
const oldCond=performanceConditions;performanceConditions=(e,d)=>{if(!isEnduranceDiscipline(d))return oldCond(e,d);const dist=ED[d].distance,h=hashString(`${s.game.season}|${e?.id}|${d}|end-cond`),f=dist/10000,o=[['Cool and still','Cool, still air gives the field close to ideal racing conditions.',0,'positive'],['Mild conditions','Mild conditions should keep environmental influence neutral.',.8*f,'neutral'],['Warm evening','The warmer air will make the closing stages more demanding.',5.5*f,'negative'],['Light breeze','A light breeze adds a small cost to athletes doing work at the front.',2.1*f,'neutral'],['Humid conditions','Humidity increases the physiological cost as the race develops.',4.2*f,'negative']][h%5];return{label:o[0],detail:o[1],effect:o[2],tone:o[3]}};
function ensureAll(){for(const n of Object.keys(COUNTRIES))s.nationPoints[n]??=0;const ids=new Set((s.athletes||[]).map(a=>a.id));SEEDS.forEach(seed=>{if(!ids.has(seed.id)){const a={...seed,medals:{g:0,s:0,b:0},profileResults:[],inSquad:seed.nation===managedNation()?false:true};ensureAthleteVisualIdentity(a);s.athletes.push(a);ids.add(a.id)}});(s.events||[]).filter(e=>!e.completed).forEach(expandEvent);s.records??={world:{},national:{}};s.records.world??={};s.records.national??={};Object.entries(WR).forEach(([d,v])=>s.records.world[d]??={value:v,holder:'World Record',nation:'WORLD',season:'Pre-career'});for(const n of Object.keys(COUNTRIES)){s.records.national[n]??={};for(const d of IDS)if(!s.records.national[n][d]){const xs=s.athletes.filter(a=>!a.retired&&a.nation===n&&a.disc===d&&Number.isFinite(a.pb)).map(a=>a.pb);if(xs.length){const best=Math.min(...xs),b=ED[d].distance>=5000?3:ED[d].distance>=1500?1:.4;s.records.national[n][d]={value:+(best-b).toFixed(2),holder:'Historic benchmark',season:'Pre-career'}}}}s.enduranceVersion=ENDURANCE_VERSION;s.seasonLeads??={}}
const oldFresh=fresh;fresh=(n='GREAT BRITAIN')=>{const st=oldFresh(n),hold=s;s=st;try{ensureAll()}finally{s=hold}return st};
if(typeof UPDATES!=='undefined'&&!UPDATES.some(u=>u.title==='Update 11 — Endurance'))UPDATES.unshift({date:'9 September 2026',title:'Update 11 — Endurance',items:['Added men’s and women’s 800m, 1500m, 5000m and 10,000m, expanding Athletics Manager from ten disciplines to eighteen.','Endurance performances now weight fitness, fatigue, conditions, pacing and race execution increasingly heavily as the distance rises.','Selection, records, rankings, scouting, National Pool depth, World Cup and Olympic qualification now recognise every new distance event.','Kenya, Ethiopia and Uganda join the simulated athletics world alongside a new generation of middle- and long-distance specialists across the existing nations.','The Sprint Coach and Sprint Centre are now the Track Coach and Track Centre so the current programme structure supports both sprint and endurance athletes.']});
ensureAll();if(typeof qualificationRoadState==='function'){qualificationRoadState();if(typeof ensureQualificationLocks==='function')ensureQualificationLocks()}save();render();if(typeof renderMenu==='function')renderMenu();
})();
